<?php

namespace ContainerDl5Ncll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanqueBusinessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Business\BanqueBusiness' shared autowired service.
     *
     * @return \App\Business\BanqueBusiness
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Business'.\DIRECTORY_SEPARATOR.'BanqueBusiness.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Backend'.\DIRECTORY_SEPARATOR.'CompteService.php';

        return $container->privates['App\\Business\\BanqueBusiness'] = new \App\Business\BanqueBusiness(($container->privates['App\\Backend\\ClientService'] ?? $container->load('getClientServiceService')), new \App\Backend\CompteService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService())));
    }
}
