<?php

namespace ContainerDl5Ncll;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Backend\ClientService' shared autowired service.
     *
     * @return \App\Backend\ClientService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Backend'.\DIRECTORY_SEPARATOR.'ClientService.php';

        return $container->privates['App\\Backend\\ClientService'] = new \App\Backend\ClientService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
